# Generated by Django 3.2.16 on 2024-05-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Пара "Рецепт - ингредиент"', 'verbose_name_plural': 'Пары "Рецепт - ингредиент"'},
        ),
    ]
