# Generated by Django 3.2.16 on 2024-05-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_recipeingredient_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=1, verbose_name='Время приготовления'),
            preserve_default=False,
        ),
    ]
