# Generated by Django 3.2.16 on 2024-05-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240505_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(default='g', max_length=50, verbose_name='Единица измерения'),
            preserve_default=False,
        ),
    ]
