# Generated by Django 3.2.16 on 2024-05-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quantity',
            new_name='amount',
        ),
    ]
