# Generated by Django 3.2.16 on 2024-05-05 18:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_quantity_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(validators=[api.models.validate_positive], verbose_name='Количество'),
        ),
    ]
