# Generated by Django 3.2.16 on 2024-05-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20240508_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
