version: '3.3'

volumes:
  media:
  static:
  db_data:


services:

  frontend:
    image: badchemist/foodgram_frontend
    volumes:
      - static:/app/result_build/build

  nginx:
    image: nginx:1.19.3
    ports:
      - "8888:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - media:/var/www/foodgram/media/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend

  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: badchemist/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/var/www/foodgram/media/
