# Generated by Django 3.2.16 on 2024-05-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_recipeingredient_unique ingredients for recipe'),
        ('users', '0003_alter_usermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='favorites',
            field=models.ManyToManyField(related_name='subscriber', to='api.Recipe'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='shopping_cart',
            field=models.ManyToManyField(related_name='cooking_chef', to='api.Recipe'),
        ),
    ]
