# Generated by Django 3.2.16 on 2024-05-07 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_recipeingredient_unique ingredients for recipe'),
        ('users', '0004_auto_20240506_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='followings',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='favorites',
            field=models.ManyToManyField(related_name='subscriber', to='api.Recipe', verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='shopping_cart',
            field=models.ManyToManyField(related_name='cooking_chef', to='api.Recipe', verbose_name='В списке покупок'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
