# Generated by Django 3.2.16 on 2024-05-08 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20240508_1512'),
        ('users', '0005_auto_20240508_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='subscriber', to='api.Recipe', verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='cooking_chef', to='api.Recipe', verbose_name='В списке покупок'),
        ),
    ]
