# Generated by Django 3.2.16 on 2024-05-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20240511_2151'),
        ('users', '0006_auto_20240508_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='api.Recipe', verbose_name='Избранное'),
        ),
    ]
